ustream-mbedtls: fix comparison of integers of different signs
Fixes following compiler extra warning:

 ustream-mbedtls.c:40:11: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
        if (slen > len)
            ~~~~ ^ ~~~

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit cd2c3d12db432dd8a484e34818d1a30f84ad9fae)